#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If you don't have
#       one, but you are running Cygwin or MSYS, install a bash shell.
#
#   (2) The shell must export the environment variable SHELL=/bin/bash
#       before calling this Library. If running locally or in a continuous
#       integration server where /bin/bash is not in the default PATH,
#       export SHELL=/bin/bash before running the build.
#
#   (3) Set the JAVA_HOME or JAVA_TOOL_OPTIONS to point to the Java version
#       to use when running the build. Note that on most modern systems the
#       JAVA_TOOL_OPTIONS is ignored when running `gradle` in the foreground.
#       See also https://gradle.org/docs/current/userguide/build_cache.html#build_cache_setup_gradle_properties
#
##############################################################################

if [ "`uname`" = "Darwin" ] ; then
    APP_HOME=`/usr/bin/dirname "$0"`
    APP_HOME=`cd "$APP_HOME" && pwd`
else
    APP_HOME=`dirname "$0"`
    APP_HOME=`cd "$APP_HOME" && /bin/pwd`
fi

export APP_HOME

app_path="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$app_path" ] ; then
    $echo "error: gradlew is not properly installed"
    exit 1
fi

app_classpath=`"$JAVA_HOME/bin/java" -cp "$app_path" org.gradle.wrapper.GradleWrapperMain --classpath-only 2>/dev/null`

if [ $? != 0 ] ; then
    $echo "error: Failed to compute classpath for gradlew"
    exit 1
fi

"$JAVA_HOME/bin/java" -cp "$app_classpath" org.gradle.wrapper.GradleWrapperMain "$@"
